# Generated by Django 4.1.1 on 2022-09-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('diary_id', models.AutoField(primary_key=True, serialize=False, verbose_name='일기_id')),
                ('title', models.CharField(max_length=20, verbose_name='제목')),
                ('content', models.CharField(max_length=200, verbose_name='본문')),
                ('password', models.CharField(max_length=120, verbose_name='비밀번호')),
                ('nickname', models.CharField(max_length=10, verbose_name='작성자별명')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='생성날짜')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='수정날짜')),
            ],
            options={
                'verbose_name': '일기',
                'verbose_name_plural': '일 목록',
                'db_table': 'diary',
            },
        ),
    ]
