# Generated by Django 4.1.1 on 2022-09-07 08:08

import diary.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='weather',
            field=models.CharField(blank=True, default=None, max_length=20, verbose_name='날씨'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='password',
            field=models.CharField(max_length=120, validators=[diary.validation.PasswordMinimumLengthValidator, diary.validation.PasswordNumbericValidator], verbose_name='비밀번호'),
        ),
    ]
